### PR TITLE
Tapo P100 / Add port as configuration option

### PR DESCRIPTION
**Pull request by ricardoboss**
I found myself needing to update the port used by the plugin and implemented it.

### CODE REVIEW

**Comment by kantlivelong** [comment]
Hi @ricardoboss,

Just curious what the use case was here since as far as I know the port is not changeable on the device.

**Comment by ricardoboss** [comment]
I tried to use a TPLink P100, but the logs indicated that it actively refused to connect on port 9999, whereas I got some response on port 80.

**Comment by ricardoboss** [comment]
@kantlivelong sooo, can you approve the PR?

**Comment by kantlivelong** [comment]
Looking at the P100 it apprears to be a Tapo device which is a little different than their Kasa line and that explains why it wouldn't work with port 9999. Without having the device I can't verify the functionality so what I'll do is keep this PR open until a few other users chime in with their results.

**Comment by ricardoboss** [comment]
Would have been nice to know which plugs are explicitly supported by this plugin instead of a generic "TP Link Smart Plug" before buying one. I admit I didn't notice it was from Tapo (which is some kind of sub-brand of TP Link) instead of TP Link prior to buying. Maybe, to prevent this from happening, you could add a list of tested and supported smart plugs to the README.

**Comment by kantlivelong** [comment]
Haven't ran into a model that hasn't worked yet. The plug you are using isn't even listed on the TPLink website so I'm not really sure what to make of it.

**Comment by ricardoboss** [comment]
Even so, at least report which plugs you have personally tested with a disclaimer for all other TP Link plugs (not that you are liable for anything, just for people like me). I'll try to get my hands on a Kasa model next.

Btw: after testing the changes proposed in this PR locally, it didn't seem to work either. So I'll just close this now.

**Comment by jneilliii** [comment]
@ricardoboss you may want to check out the other tplink plugin (not mine). I think it might work with your device.

**Comment by ricardoboss** [comment]
@jneilliii you mean this one? https://github.com/Tyfy/OctoPrint-TapoSmartplug

**Comment by jneilliii** [comment]
yeah either that one (specific to Tapo devices) or I think this one might work. https://plugins.octoprint.org/plugins/TpLinkAutoShutdown/

**Comment by jneilliii** [comment]
It uses this library to handle connecting. https://github.com/python-kasa/python-kasa, so in theory anything supported by that python module will work. Looking at the repo, it seems you might be better off with the Tapo one as P100 links to a different module.

**Comment by ricardoboss** [comment]
Thanks @jneilliii for the tip and @Tyfy for the effort! The plugin works just as I hoped it would.

**Pull request closed without merging**
